
version: "3.0"
services:
  dtbank_db:
    container_name: dtbank_container
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "33061:3306"
    command: --init-file /docker-entrypoint-initdb.d/create_schema.sql    
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: DTBank
      MYSQL_USER: myroot
      MYSQL_PASSWORD: myroot